# Generated by Django 6.0.3 on 2026-04-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="calories",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="meal",
            name="full_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="origin",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="meal",
            name="rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meal",
            name="reviews",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="meal",
            name="tag",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="meal",
            name="time",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
