# Generated by Django 6.0.3 on 2026-04-02 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recommendations",
            "0002_meal_calories_meal_full_description_meal_origin_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["category"], name="recommendat_categor_2d26e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["-purchase_count", "-view_count"],
                name="recommendat_purchas_5469bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(fields=["rating"], name="recommendat_rating_ba05b6_idx"),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["created_at"], name="recommendat_created_d01e03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["user", "timestamp"], name="recommendat_user_id_9130e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["meal", "interaction_type"],
                name="recommendat_meal_id_bc07e0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["timestamp"], name="recommendat_timesta_eec1c9_idx"
            ),
        ),
    ]
